version: "3"

services:
    nginx:
        container_name: "NGINX"
        build: ./requirements/nginx/
        volumes:
            - "./requirements/nginx/conf:/etc/nginx/http.d/"
            - "./requirements/nginx/tools:/etc/nginx/tools/"
            - "./requirements/nginx/data:/var/www/"
        ports:
            - "443:443"
        restart: always
    
    mariadb:
        container_name: "mariadb"
        build:
            context: .
            dockerfile: ./requirements/mariadb/Dockerfile
            args:
                DB_NAME: ${DB_NAME}
                DB_USER: ${DB_USER}
                DB_PASS: ${DB_PASS}
                DB_ROOT: ${DB_ROOT}
        ports:
            - "3306:3306"
