version: "3.5"

services:
    nginx:
        container_name: "NGINX"
        build: ./requirements/nginx/
        volumes:
            - "./requirements/nginx/conf:/etc/nginx/http.d/"
            - "./requirements/nginx/tools:/etc/nginx/tools/"
            - "wp-volume:/var/www/"
        ports:
            - "443:443"
        depends_on:
            - wordpress
        restart: always
        networks:
            - inception
    
    mariadb:
        container_name: "mariadb"
        build:
            context: .
            dockerfile: ./requirements/mariadb/Dockerfile
            args:
                DB_NAME: ${DB_NAME}
                DB_USER: ${DB_USER}
                DB_PASS: ${DB_PASS}
                DB_ROOT: ${DB_ROOT}
        ports:
            - "3306:3306"
        networks:
            - inception

    wordpress:
        container_name: wordpress
        build:
            context: .
            dockerfile: requirements/wordpress/Dockerfile
            args:
                DB_NAME: ${DB_NAME}
                DB_USER: ${DB_USER}
                DB_PASS: ${DB_PASS}
                DB_ROOT: ${DB_ROOT}
        ports:
            - "9000:9000"
        depends_on:
            - mariadb
        restart: always
        volumes:
            - wp-volume:/var/www/
        networks:
            - inception

volumes:
    wp-volume:
        driver_opts:
            o: bind
            type: none
            device: /home/${USER}/data/wordpress

    db-volume:
        driver_opts:
            o: bind
            type: none
            device: /home/${USER}/data/mariadb

networks:
    inception:
        driver: bridge
