version: "3.5"

services:
    nginx:
        build: ./requirements/nginx/
        container_name: "NGINX"
        volumes:
            - "./requirements/nginx/conf:/etc/nginx/http.d/"
            - "./requirements/nginx/tools:/etc/nginx/tools/"
            - "./requirements/nginx/data:/var/www/"
        ports:
            - "443:443"
        restart: always
